#?  development version
#* flutter --version
# Flutter 3.16.4 • channel stable • https://github.com/flutter/flutter.git
# Framework • revision 2e9cb0aa71 (9 days ago) • 2023-12-11 14:35:13 -0700
# Engine • revision 54a7145303
# Tools • Dart 3.2.3 • DevTools 2.28.4

name: mmfsl
description: "Assignment - Mahendra Finance"
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
